version: '3.9'
services:
  flatcam:
    image: fazleskhan/flatcam:dev
    container_name: flatcam-container
    ports:
      - "3389:3389"
    environment:
      - DISPLAY=host.docker.internal:0.0
    networks:
      static-network:
        ipv4_address: 172.20.128.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.128.0/16
